// src/pages/favorite/index.tsx
import React from 'react'
import { View, Text } from '@tarojs/components'
import EmptyState from '@/components/EmptyState'
import styles from './index.module.scss'

const FavoritePage: React.FC = () => {
  return (
    <View className={styles.container}>
      <View className={styles.content}>
        <EmptyState
          icon='❤️'
          title='收藏功能'
          description='收藏功能开发中，敬请期待...'
        />
      </View>
    </View>
  )
}

export default FavoritePage

// src/pages/favorite/index.vue
<script setup lang="ts">
import { ref } from 'vue'
import { View, Text, ScrollView } from '@tarojs/components'
import EmptyState from '@/components/EmptyState'
import styles from './index.module.scss'

const favorites = ref([])
</script>

<template>
  <view :class="styles.container">
    <scroll-view :class="styles.content" scroll-y>
      <EmptyState
        icon="❤️"
        title="暂无收藏商品"
        description="遇到喜欢的商品就收藏起来吧"
      />
    </scroll-view>
  </view>
</template>
