// src/pages/order/index.vue
<script setup lang="ts">
import { ref } from 'vue'
import { View, Text, ScrollView } from '@tarojs/components'
import EmptyState from '@/components/EmptyState'
import styles from './index.module.scss'

const tabs = ['全部', '待付款', '待发货', '待收货', '已完成']
const activeTab = ref(0)

const handleTabClick = (index: number) => {
  activeTab.value = index
}
</script>

<template>
  <view :class="styles.container">
    <view :class="styles.tabs">
      <view
        v-for="(tab, index) in tabs"
        :key="index"
        :class="[styles.tabItem, activeTab === index && styles.active]"
        @click="handleTabClick(index)"
      >
        <text :class="styles.tabText">{{ tab }}</text>
      </view>
    </view>

    <scroll-view :class="styles.content" scroll-y>
      <EmptyState
        icon="📦"
        title="暂无订单"
        description="快去挑选心仪的商品吧"
      />
    </scroll-view>
  </view>
</template>

// src/pages/order/index.tsx
import React from 'react'
import { View, Text } from '@tarojs/components'
import EmptyState from '@/components/EmptyState'
import styles from './index.module.scss'

const OrderPage: React.FC = () => {
  return (
    <View className={styles.container}>
      <View className={styles.content}>
        <EmptyState
          icon='📋'
          title='订单功能'
          description='订单功能开发中，敬请期待...'
        />
      </View>
    </View>
  )
}

export default OrderPage
