// src/pages/category/index.tsx
import React, { useState, useMemo, useCallback } from 'react'
import { View, Text, ScrollView } from '@tarojs/components'
import { Product } from '@/types/product'
import { categories, getProductsByCategory } from '@/data/products'
import ProductCard from '@/components/ProductCard'
import CompareBar from '@/components/CompareBar'
import EmptyState from '@/components/EmptyState'
import classnames from 'classnames'
import styles from './index.module.scss'

type SortType = 'default' | 'sales' | 'price-asc' | 'price-desc' | 'rating'

const filters = [
  { key: 'default', label: '综合' },
  { key: 'sales', label: '销量' },
  { key: 'price-asc', label: '价格↑' },
  { key: 'price-desc', label: '价格↓' },
  { key: 'rating', label: '评分' }
]

const CategoryPage: React.FC = () => {
  const [activeCategory, setActiveCategory] = useState<string>('1')
  const [sortType, setSortType] = useState<SortType>('default')

  const handleCategoryClick = useCallback((categoryId: string) => {
    setActiveCategory(categoryId)
    console.log('[Category] switch category:', categoryId)
  }, [])

  const handleSortClick = useCallback((key: SortType) => {
    setSortType(key)
    console.log('[Category] sort by:', key)
  }, [])

  const sortedProducts = useMemo(() => {
    let list: Product[] = getProductsByCategory(activeCategory)
    switch (sortType) {
      case 'sales':
        return [...list].sort((a, b) => b.sales - a.sales)
      case 'price-asc':
        return [...list].sort((a, b) => a.price - b.price)
      case 'price-desc':
        return [...list].sort((a, b) => b.price - a.price)
      case 'rating':
        return [...list].sort((a, b) => b.rating - a.rating)
      default:
        return list
    }
  }, [activeCategory, sortType])

  return (
    <View className={styles.container}>
      <ScrollView className={styles.sidebar} scrollY>
        {categories.map(category => (
          <View
            key={category.id}
            className={classnames(styles.categoryItem, {
              [styles.categoryItemActive]: activeCategory === category.id
            })}
            onClick={() => handleCategoryClick(category.id)}
          >
            <Text className={styles.categoryIcon}>{category.icon}</Text>
            <Text>{category.name}</Text>
          </View>
        ))}
      </ScrollView>

      <View className={styles.main}>
        <View className={styles.filterBar}>
          {filters.map(filter => (
            <Text
              key={filter.key}
              className={classnames(styles.filterItem, {
                [styles.filterItemActive]: sortType === filter.key
              })}
              onClick={() => handleSortClick(filter.key as SortType)}
            >
              {filter.label}
            </Text>
          ))}
        </View>

        <ScrollView className={styles.productScroll} scrollY>
          {sortedProducts.length > 0 ? (
            <View className={styles.productGrid}>
              {sortedProducts.map(product => (
                <View key={product.id} className={styles.productItem}>
                  <ProductCard product={product} />
                </View>
              ))}
            </View>
          ) : (
            <EmptyState
              icon='🍽️'
              title='该分类暂无商品'
              description='去看看其他分类吧~'
            />
          )}
        </ScrollView>
      </View>

      <CompareBar />
    </View>
  )
}

export default CategoryPage

// src/pages/category/index.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { View, Text, ScrollView } from '@tarojs/components'
import Taro from '@tarojs/taro'
import type { Product, Category } from '@/types'
import { categories, getProductsByCategory } from '@/mock/products'
import ProductCard from '@/components/ProductCard.vue'
import CompareBar from '@/components/CompareBar.vue'
import { formatPrice } from '@/utils'
import styles from './index.module.scss'

const selectedCategory = ref('all')
const sortType = ref('default')

const categoryList = computed(() => categories)
const productList = computed(() => getProductsByCategory(selectedCategory.value))

const handleCategoryClick = (categoryId: string) => {
  selectedCategory.value = categoryId
  console.log('[Category] 选择分类:', categoryId)
}

const handleSortChange = (type: string) => {
  sortType.value = type
  console.log('[Category] 切换排序:', type)
}

const handleProductClick = (product: Product) => {
  Taro.navigateTo({
    url: `/pages/detail/index?id=${product.id}`
  })
}

const sortedProducts = computed(() => {
  const list = [...productList.value]
  
  switch (sortType.value) {
    case 'price-asc':
      return list.sort((a, b) => a.price - b.price)
    case 'price-desc':
      return list.sort((a, b) => b.price - a.price)
    case 'sales':
      return list.sort((a, b) => b.sales - a.sales)
    case 'rating':
      return list.sort((a, b) => b.rating - a.rating)
    default:
      return list
  }
})
</script>

<template>
  <view :class="styles.page">
    <view :class="styles.header">
      <view :class="styles.sortBar">
        <view
          :class="[styles.sortItem, sortType === 'default' && styles.active]"
          @click="handleSortChange('default')"
        >
          <text>综合</text>
        </view>
        <view
          :class="[styles.sortItem, sortType === 'sales' && styles.active]"
          @click="handleSortChange('sales')"
        >
          <text>销量</text>
        </view>
        <view
          :class="[styles.sortItem, sortType === 'price-asc' && styles.active]"
          @click="handleSortChange('price-asc')"
        >
          <text>价格↑</text>
        </view>
        <view
          :class="[styles.sortItem, sortType === 'price-desc' && styles.active]"
          @click="handleSortChange('price-desc')"
        >
          <text>价格↓</text>
        </view>
        <view
          :class="[styles.sortItem, sortType === 'rating' && styles.active]"
          @click="handleSortChange('rating')"
        >
          <text>评分</text>
        </view>
      </view>
    </view>

    <view :class="styles.content">
      <scroll-view :class="styles.sidebar" scroll-y>
        <view
          v-for="category in categoryList"
          :key="category.id"
          :class="[
            styles.categoryItem,
            selectedCategory === category.id && styles.active
          ]"
          @click="handleCategoryClick(category.id)"
        >
          <text :class="styles.categoryIcon">{{ category.icon }}</text>
          <text :class="styles.categoryName">{{ category.name }}</text>
        </view>
      </scroll-view>

      <scroll-view :class="styles.productList" scroll-y>
        <view :class="styles.productGrid">
          <ProductCard
            v-for="product in sortedProducts"
            :key="product.id"
            :product="product"
            @click="handleProductClick"
          />
        </view>
        <view v-if="sortedProducts.length === 0" :class="styles.empty">
          <text>该分类暂无商品</text>
        </view>
        <view :class="styles.footer">
          <text>— 已经到底啦 —</text>
        </view>
      </scroll-view>
    </view>

    <CompareBar />
  </view>
</template>
