// src/pages/mine/index.tsx
import React, { useCallback } from 'react'
import { View, Text, Button } from '@tarojs/components'
import Taro from '@tarojs/taro'
import { useCompareStore } from '@/store/compareStore'
import styles from './index.module.scss'

const orderTabs = [
  { key: 'pending', icon: '💰', label: '待付款' },
  { key: 'shipping', icon: '🚚', label: '待发货' },
  { key: 'receiving', icon: '📦', label: '待收货' },
  { key: 'review', icon: '⭐', label: '待评价' }
]

const menuItems = [
  { key: 'favorite', icon: '❤️', label: '我的收藏', path: '/pages/favorite/index' },
  { key: 'order', icon: '📋', label: '全部订单', path: '/pages/order/index' },
  { key: 'address', icon: '📍', label: '收货地址', path: '' },
  { key: 'service', icon: '💬', label: '联系客服', path: '' },
  { key: 'settings', icon: '⚙️', label: '设置', path: '' }
]

const MinePage: React.FC = () => {
  const { compareList } = useCompareStore()

  const handleMenuClick = useCallback((item: typeof menuItems[0]) => {
    if (!item.path) {
      Taro.showToast({
        title: '功能开发中',
        icon: 'none'
      })
      return
    }
    if (item.path.startsWith('/pages/order') || item.path.startsWith('/pages/favorite')) {
      Taro.navigateTo({
        url: item.path
      })
    }
    console.log('[Mine] click menu:', item.key)
  }, [])

  const handleOrderClick = useCallback((key: string) => {
    Taro.navigateTo({
      url: `/pages/order/index?status=${key}`
    })
  }, [])

  const handleGoCompare = useCallback(() => {
    Taro.switchTab({
      url: '/pages/compare/index'
    })
  }, [])

  return (
    <View className={styles.container}>
      <View className={styles.header}>
        <View className={styles.avatar}>👤</View>
        <View className={styles.userInfo}>
          <Text className={styles.userName}>鲜果达人</Text>
          <Text className={styles.userDesc}>已为您优选新鲜好物</Text>
        </View>
      </View>

      {compareList.length > 0 && (
        <View className={styles.compareTip}>
          <Text className={styles.tipIcon}>📊</Text>
          <Text className={styles.tipText}>
            您已选{compareList.length}件商品待对比
          </Text>
          <Button className={styles.tipBtn} onClick={handleGoCompare}>去对比</Button>
        </View>
      )}

      <View className={styles.orderSection}>
        <View className={styles.sectionTitle}>
          <Text className={styles.titleText}>我的订单</Text>
          <Button className={styles.moreLink} onClick={() => handleOrderClick('all')}>
            全部订单 →
          </Button>
        </View>
        <View className={styles.orderTabs}>
          {orderTabs.map(tab => (
            <View
              key={tab.key}
              className={styles.orderTab}
              onClick={() => handleOrderClick(tab.key)}
            >
              <View className={styles.orderIcon}>{tab.icon}</View>
              <Text className={styles.orderLabel}>{tab.label}</Text>
            </View>
          ))}
        </View>
      </View>

      <View className={styles.menuSection}>
        {menuItems.slice(0, 2).map(item => (
          <View
            key={item.key}
            className={styles.menuItem}
            onClick={() => handleMenuClick(item)}
          >
            <View className={styles.menuIcon}>{item.icon}</View>
            <Text className={styles.menuLabel}>{item.label}</Text>
            <Text className={styles.menuArrow}>›</Text>
          </View>
        ))}
      </View>

      <View className={styles.toolSection}>
        {menuItems.slice(2).map(item => (
          <View
            key={item.key}
            className={styles.menuItem}
            onClick={() => handleMenuClick(item)}
          >
            <View className={styles.menuIcon}>{item.icon}</View>
            <Text className={styles.menuLabel}>{item.label}</Text>
            <Text className={styles.menuArrow}>›</Text>
          </View>
        ))}
      </View>
    </View>
  )
}

export default MinePage

// src/pages/mine/index.vue
<script setup lang="ts">
import { computed } from 'vue'
import { View, Text } from '@tarojs/components'
import Taro from '@tarojs/taro'
import { useCompareStore } from '@/stores/compare'
import { useCartStore } from '@/stores/cart'
import styles from './index.module.scss'

const compareStore = useCompareStore()
const cartStore = useCartStore()

const compareCount = computed(() => compareStore.count)
const cartCount = computed(() => cartStore.totalCount)

const menuItems = [
  { id: 'order', icon: '📋', label: '我的订单', path: '/pages/order/index' },
  { id: 'favorite', icon: '❤️', label: '我的收藏', path: '/pages/favorite/index' },
  { id: 'compare', icon: '⚖️', label: '商品对比', path: '/pages/compare/index', badge: compareCount },
  { id: 'address', icon: '📍', label: '收货地址', path: '' },
  { id: 'service', icon: '💬', label: '联系客服', path: '' },
  { id: 'settings', icon: '⚙️', label: '设置', path: '' }
]

const handleMenuClick = (item: typeof menuItems[0]) => {
  console.log('[Mine] 点击菜单:', item.label)
  if (item.path) {
    if (item.id === 'compare') {
      Taro.switchTab({ url: item.path })
    } else {
      Taro.navigateTo({ url: item.path })
    }
  } else {
    Taro.showToast({
      title: '功能开发中',
      icon: 'none'
    })
  }
}
</script>

<template>
  <scroll-view :class="styles.page" scroll-y>
    <view :class="styles.header">
      <view :class="styles.avatar">
        <text :class="styles.avatarIcon">👤</text>
      </view>
      <view :class="styles.userInfo">
        <text :class="styles.userName">生鲜爱好者</text>
        <text :class="styles.userDesc">已注册30天</text>
      </view>
    </view>

    <view v-if="compareCount > 0" :class="styles.compareNotice" @click="handleMenuClick(menuItems[2])">
      <text :class="styles.compareIcon">⚖️</text>
      <text :class="styles.compareText">您有 {{ compareCount }} 件商品正在对比中</text>
      <text :class="styles.compareArrow">›</text>
    </view>

    <view :class="styles.orderSection">
      <view :class="styles.sectionHeader">
        <text :class="styles.sectionTitle">我的订单</text>
        <text :class="styles.sectionMore">查看全部 ›</text>
      </view>
      <view :class="styles.orderTabs">
        <view :class="styles.orderTab">
          <text :class="styles.orderIcon">💳</text>
          <text :class="styles.orderLabel">待付款</text>
        </view>
        <view :class="styles.orderTab">
          <text :class="styles.orderIcon">📦</text>
          <text :class="styles.orderLabel">待发货</text>
        </view>
        <view :class="styles.orderTab">
          <text :class="styles.orderIcon">🚚</text>
          <text :class="styles.orderLabel">待收货</text>
        </view>
        <view :class="styles.orderTab">
          <text :class="styles.orderIcon">⭐</text>
          <text :class="styles.orderLabel">待评价</text>
        </view>
      </view>
    </view>

    <view :class="styles.menuSection">
      <view
        v-for="item in menuItems"
        :key="item.id"
        :class="styles.menuItem"
        @click="handleMenuClick(item)"
      >
        <view :class="styles.menuLeft">
          <text :class="styles.menuIcon">{{ item.icon }}</text>
          <text :class="styles.menuLabel">{{ item.label }}</text>
        </view>
        <view :class="styles.menuRight">
          <text v-if="item.badge && item.badge > 0" :class="styles.badge">
            {{ item.badge }}
          </text>
          <text :class="styles.menuArrow">›</text>
        </view>
      </view>
    </view>
  </scroll-view>
</template>
